# 上下文优先级常量（越低越先被压缩）
PRIORITY_SYSTEM_PROMPT = 1      # 最高
PRIORITY_CURRENT_TASK = 1
PRIORITY_TOOL_SCHEMAS = 2
PRIORITY_SKILL_MANIFESTS = 2
PRIORITY_RECENT_OBSERVATIONS = 3
PRIORITY_WORKING_MEMORY = 3
PRIORITY_OLDER_OBSERVATIONS = 4
PRIORITY_SHORT_TERM_MEMORY = 4
PRIORITY_LONG_TERM_MEMORY = 5    # 最低
